name: "Checkout and Build"
description: ""
inputs:
  path:
    description: "Path"
    required: true
  satis_key:
    description: "SatisPress Key (packages.saucal.com)"
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Path Setup
      shell: bash
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH

    - name: Maybe Build And Cleanup
      shell: bash
      env:
        BUILD_DIR: ${{ inputs.path }}
      run: maybe-build.sh
